title: Jakub Rogalski
tagline: Portfolio site
description: A portfolio site for Machine Learning Projects.
url: "https://cubeen.github.io"
baseurl: "/my-site"
avatar: /assets/img/rogalski.jpeg
author: Jakub Rogalski
timezone: Europe/London
lang: en

# Theme Selection (Required for GitHub Pages)
remote_theme: cotes2020/jekyll-theme-chirpy

# Pagination (Fixes the blank homepage)
paginate: 10

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Build Settings
markdown: kramdown
highlighter: rouge